package pipefn

import (
	"fmt"
	"iter"
	"sync"
)

type (
	// Pipe represents a lazily-evaluated sequence of values of type T.
	//
	// Each transformation (Map, TryMap, Flatten etc.) produces a new Pipe that wraps the previous one.
	//
	// Errors generated by faillible stages (e.g. TryMap) are sent on the shared error channel.
	//
	// A Pipe is consumed when its sequence is iterated, typically through Results,
	// Values, or ForEach. Once consumed, a Pipe cannot be reused.
	// Refer to each consuming method's documentation for details on their behavior.
	Pipe[T any] struct {
		seq    iter.Seq[T]
		errors chan error
	}

	// PipeError represents an error that occured inside a pipeline
	PipeError struct {
		// The item that generated the error
		Item any
		// The actual error
		Reason error
	}
)

// From creates a Pipe that produces values from the provided iter.Seq.
//
// From panics if seq is nil.
func From[T any](seq iter.Seq[T]) Pipe[T] {

	if seq == nil {
		panic("pipefn.From: nil seq")
	}

	p := Pipe[T]{
		errors: make(chan error),
	}

	p.seq = func(yield func(T) bool) {
		defer close(p.errors)
		for item := range seq {
			if !yield(item) {
				return
			}
		}
	}

	return p
}

// FromSlice creates a Pipe that produces the elements of elems in order.
//
// The resulting Pipe yields each element of the slice sequentially.
// The slice is not copied; iteration reads directly from elems.
//
// If elems is nil, the resulting Pipe behaves as an empty pipe.
func FromSlice[T any](elems []T) Pipe[T] {
	return From(func(yield func(T) bool) {
		for _, e := range elems {
			if !yield(e) {
				return
			}
		}
	})
}

// FromChan creates a Pipe that produces values received from ch.
//
// The resulting Pipe yields each value read from the channel until the
// channel is closed. If the downstream consumer stops iteration early
// (i.e., yield returns false), iteration stops immediately and remaining
// values in the channel are ignored.
//
// FromChan does not close the provided channel; channel lifecycle remains
// the responsibility of the caller.
func FromChan[T any](ch <-chan T) Pipe[T] {
	return From(func(yield func(T) bool) {
		for c := range ch {
			if !yield(c) {
				return
			}
		}
	})
}

// Empty returns a Pipe that produces no values.
//
// The returned Pipe completes immediately when iterated and
// yields no elements and no errors.
func Empty[T any]() Pipe[T] {
	return From(func(yield func(T) bool) {})
}

// Results returns an iterator that yields the values produced by p,
// and a channel that emits the errors produced by p.
//
// The returned iterator may be consumed exactly once.
// Starting iteration consumes the pipe; subsequent iterations are undefined.
//
// Callers must drain the errors chan. If errors are not consumed,
// the pipeline may block when a stage attempts to send an error.
//
// Callers that wish to consume a pipe without having to handle errors should
// use p.Values() instead.
//
// All errors emitted by Results will be of type *PipeError.
//
// Typical usage:
//
//	values, errs := p.Results()
//
//	var wg sync.WaitGroup
//	wg.Add(1)
//	go func() {
//	    defer wg.Done()
//	    for err := range errs {
//		perr := err.(*PipeError)
//	        log.Printf("pipeline error: item %v: %s", perr.Item, perr.Reason)
//	    }
//	}()
//
//	for v := range values {
//	    fmt.Println("value:", v)
//	}
//	wg.Wait()
//	// here, both values and errs have been fully drained.
func (p Pipe[T]) Results() (iter.Seq[T], <-chan error) {
	return p.seq, p.errors
}

// Values returns the sequence of values produced by p.
//
// Values behaves like Results, except that the error sequence is consumed
// internally and discarded. This allows callers who do not care about errors
// to ignore them while still ensuring the pipe completes correctly.
//
// The returned iterator may be consumed exactly once.
// Starting iteration consumes the pipe; subsequent iterations are undefined.
//
// Typical usage:
//
//	for v := range p.Values() {
//		...
//	}
func (p Pipe[T]) Values() (values iter.Seq[T]) {
	values, errors := p.Results()
	go func() {
		for range errors {
		}
	}()
	return values
}

// ForEach consumes all values from the Pipe, invoking consumeFn for each.
//
// Errors produced by the pipe are forwarded to errorFn.
//
// The order of calls to consumeFn relative to errorFn is not guaranteed.
// If both handlers access shared state, the caller must synchronize access.
//
// ForEach blocks until all values and errors have been processed.
func (p Pipe[T]) ForEach(consumeFn func(item T), errorFn func(err error)) {
	values, errors := p.Results()
	var errorWg sync.WaitGroup
	errorWg.Add(1)
	go func() {
		defer errorWg.Done()
		for err := range errors {
			errorFn(err)
		}
	}()
	for i := range values {
		consumeFn(i)
	}
	errorWg.Wait()
}

// Collect consumes the entire Pipe and returns two slices containing all emitted
// values and all emitted errors, respectively.
//
// Values are collected in the order they are produced by the Pipe.
// Errors are collected in the order they are emitted.
//
// Collect fully drains the Pipe; after calling it, the Pipe cannot be consumed again.
func (p Pipe[T]) Collect() ([]T, []error) {
	var (
		values []T
		errors []error
	)

	p.ForEach(func(item T) {
		values = append(values, item)
	}, func(err error) {
		errors = append(errors, err)
	})

	return values, errors
}

// CollectValues consumes the entire Pipe and returns a slice containing all
// emitted values. Errors, if any, are ignored.
//
// Values are collected in the order they are produced by the Pipe.
//
// CollectValues fully drains the Pipe; after calling it, the Pipe cannot be
// consumed again.
func (p Pipe[T]) CollectValues() []T {
	var values []T
	p.ForEach(func(item T) {
		values = append(values, item)
	}, func(err error) {})
	return values
}

// Tap modifies p so that tapFn is called for each element that passes through p.
// The tap function is called before the element is yielded.
//
// Calling Tap multiple times will chain tap functions in the order they were added.
//
// Tap panics if tapFn is nil.
func (p *Pipe[T]) Tap(tapFn func(T)) {

	if tapFn == nil {
		panic("Pipe.Tap: tapFn cannot be nil")
	}

	originalIt := p.seq
	p.seq = func(yield func(T) bool) {
		for i := range originalIt {
			tapFn(i)
			if !yield(i) {
				return
			}
		}
	}
}

func (pe *PipeError) Error() string {
	return fmt.Sprintf("%+v: %s", pe.Item, pe.Reason)
}
